/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.Auditoria;
import Modelo.ConexionDB;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Duvan
 */
public class FRMAuditoria extends javax.swing.JInternalFrame {

    /**
     * Creates new form FRMAuditoria
     */
    public FRMAuditoria() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void llenarTabla()
    {
     Auditoria unaAuditoria = new Auditoria();
     DefaultTableModel tabla = (DefaultTableModel )TBLAuditoria.getModel();
     Iterator<Auditoria> itAuditoria = unaAuditoria.listar();
     Object[] filaAuditoria = new Object[TBLAuditoria.getColumnCount()];
     tabla.setNumRows(0);
        while (itAuditoria.hasNext()) {            
            unaAuditoria = itAuditoria.next();
            filaAuditoria[0] = unaAuditoria.getIdAuditoria();
            filaAuditoria[1] = unaAuditoria.getDescripcionAuditoria();
            filaAuditoria[2] = unaAuditoria.getFechaAuditoria();
            tabla.addRow(filaAuditoria);
        }
    }
    
    //LLENAR TABLA CON BUSQUEDA
    private void llenarTablaConBusqueda(String busqueda)
    {
    Auditoria unaAuditoria = new Auditoria();
     DefaultTableModel tabla = (DefaultTableModel )TBLAuditoria.getModel();
     Iterator<Auditoria> itAuditoria = unaAuditoria.buscar(busqueda);
     Object[] filaAuditoria = new Object[TBLAuditoria.getColumnCount()];
     tabla.setNumRows(0);
        while (itAuditoria.hasNext()) {            
            unaAuditoria = itAuditoria.next();
            filaAuditoria[0] = unaAuditoria.getIdAuditoria();
            filaAuditoria[1] = unaAuditoria.getDescripcionAuditoria();
            filaAuditoria[2] = unaAuditoria.getFechaAuditoria();
            ((DefaultTableModel)TBLAuditoria.getModel()).addRow(filaAuditoria);
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLAuditoria = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        BTNCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TXTBuscarAuditoria = new javax.swing.JTextField();
        BTNBuscar = new javax.swing.JButton();
        BTNLimpiar = new javax.swing.JButton();
        BTNReporteAuditoria = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Auditoria");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Detalle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        TBLAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "                 Id Auditoria", "                  Descripcion", "                  Fecha "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLAuditoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLAuditoriaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLAuditoria);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        BTNCerrar.setBackground(new java.awt.Color(255, 0, 0));
        BTNCerrar.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Buscar");

        TXTBuscarAuditoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarAuditoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarAuditoriaFocusLost(evt);
            }
        });
        TXTBuscarAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTBuscarAuditoriaActionPerformed(evt);
            }
        });

        BTNBuscar.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        BTNBuscar.setText("Buscar");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        BTNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiar.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        BTNLimpiar.setText("Limpiar");
        BTNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarActionPerformed(evt);
            }
        });

        BTNReporteAuditoria.setBackground(new java.awt.Color(153, 0, 153));
        BTNReporteAuditoria.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        BTNReporteAuditoria.setText("Reporte");
        BTNReporteAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReporteAuditoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXTBuscarAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BTNBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(BTNReporteAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTBuscarAuditoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscar)
                    .addComponent(BTNCerrar)
                    .addComponent(BTNLimpiar)
                    .addComponent(BTNReporteAuditoria))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBLAuditoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLAuditoriaMouseClicked
         
    }//GEN-LAST:event_TBLAuditoriaMouseClicked

    private void TXTBuscarAuditoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarAuditoriaFocusGained
        if (TXTBuscarAuditoria.getText().equals("Escriba texto a buscar")) {
            TXTBuscarAuditoria.setText("");
        }
    }//GEN-LAST:event_TXTBuscarAuditoriaFocusGained

    private void TXTBuscarAuditoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarAuditoriaFocusLost
        if (TXTBuscarAuditoria.getText().isEmpty()) {
            TXTBuscarAuditoria.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarAuditoriaFocusLost

    private void TXTBuscarAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTBuscarAuditoriaActionPerformed
        
    }//GEN-LAST:event_TXTBuscarAuditoriaActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        llenarTablaConBusqueda(TXTBuscarAuditoria.getText());
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void BTNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarActionPerformed
        llenarTabla();
    }//GEN-LAST:event_BTNLimpiarActionPerformed

    private void BTNReporteAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReporteAuditoriaActionPerformed
     
      
    }//GEN-LAST:event_BTNReporteAuditoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNLimpiar;
    private javax.swing.JButton BTNReporteAuditoria;
    private javax.swing.JTable TBLAuditoria;
    private javax.swing.JTextField TXTBuscarAuditoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
