/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorCompra;
import Modelo.Cliente;
import Modelo.Compra;
import Modelo.ConexionDB;
import Modelo.Empleado;
import Modelo.Producto;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Duvan
 */
public class FRMCompra extends javax.swing.JInternalFrame {

   ControladorCompra compraController = new ControladorCompra();
   
    public FRMCompra() {
        initComponents();
       TXTIdCompra.setValue(0);
       TXTIdCompra.setVisible(false);
       llenarTabla();
       limpiarFormulario();
       llenarComboCliente();
       llenarComboProducto();
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TXTBuscarCompra = new javax.swing.JTextField();
        BTNBuscarCompra = new javax.swing.JButton();
        CBOCliente = new javax.swing.JComboBox<Cliente>();
        TXTIdCompra = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        CBOProducto = new javax.swing.JComboBox<Producto>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLCompra = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BTNInsertar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNLimpiar = new javax.swing.JButton();
        BTNCerrar = new javax.swing.JButton();
        BTNReporteCompra = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Compra");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Ingrese Datos"));

        jLabel1.setText("Cliente ");

        jLabel2.setText("Buscar");

        TXTBuscarCompra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarCompraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarCompraFocusLost(evt);
            }
        });

        BTNBuscarCompra.setText("Buscar");
        BTNBuscarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarCompraActionPerformed(evt);
            }
        });

        CBOCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBOCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOClienteActionPerformed(evt);
            }
        });

        jLabel3.setText("Producto");

        CBOProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TXTBuscarCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNBuscarCompra)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(CBOCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(TXTIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(25, 25, 25)
                                .addComponent(CBOProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TXTIdCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBOCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBOProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTBuscarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscarCompra))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TBLCompra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TBLCompra.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        TBLCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "ID", "                   Cliente", "                   Producto Vendido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLCompra);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Opciones"));

        BTNInsertar.setBackground(new java.awt.Color(51, 255, 51));
        BTNInsertar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNInsertar.setText("Guardar");
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });

        BTNModificar.setBackground(new java.awt.Color(51, 255, 255));
        BTNModificar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BTNEliminar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        BTNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNLimpiar.setText("Limpiar");
        BTNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarActionPerformed(evt);
            }
        });

        BTNCerrar.setBackground(new java.awt.Color(102, 102, 102));
        BTNCerrar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        BTNReporteCompra.setBackground(new java.awt.Color(204, 0, 204));
        BTNReporteCompra.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNReporteCompra.setText("Reporte");
        BTNReporteCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReporteCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEliminar)
                .addGap(18, 18, 18)
                .addComponent(BTNLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(BTNReporteCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNInsertar)
                    .addComponent(BTNModificar)
                    .addComponent(BTNEliminar)
                    .addComponent(BTNLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNCerrar)
                    .addComponent(BTNReporteCompra))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        compraController.controlarAccion(evt,obtenerCompra());
        limpiarFormulario();
    }//GEN-LAST:event_BTNInsertarActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
        compraController.controlarAccion(evt,obtenerCompra());
        limpiarFormulario();
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        compraController.controlarAccion(evt,obtenerCompra());
        limpiarFormulario();
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarActionPerformed
        limpiarFormulario();
        
    }//GEN-LAST:event_BTNLimpiarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
       doDefaultCloseAction();
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void TBLCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLCompraMouseClicked
        if (evt.getClickCount()==1) {
            int fila = TBLCompra.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                TXTIdCompra.setValue((Integer)  TBLCompra.getValueAt(fila, 0));
                CBOCliente.setSelectedItem((Cliente)TBLCompra.getValueAt(fila, 1));
                CBOProducto.setSelectedItem((Producto)TBLCompra.getValueAt(fila, 2));
                BTNEliminar.setEnabled(true);
                BTNModificar.setEnabled(true);
               
                
            }
        }
    }//GEN-LAST:event_TBLCompraMouseClicked

    private void TXTBuscarCompraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCompraFocusGained
         if (TXTBuscarCompra.getText().equals("Escriba texto a buscar")) {
            TXTBuscarCompra.setText("");
        } 
    }//GEN-LAST:event_TXTBuscarCompraFocusGained

    private void TXTBuscarCompraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarCompraFocusLost
        if (TXTBuscarCompra.getText().isEmpty()){
            TXTBuscarCompra.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarCompraFocusLost

    private void CBOClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOClienteActionPerformed

    private void BTNBuscarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarCompraActionPerformed
        llenarTablaConBusqueda(TXTBuscarCompra.getText());
    }//GEN-LAST:event_BTNBuscarCompraActionPerformed

    private void BTNReporteCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReporteCompraActionPerformed
       JasperReport jrReporte = null;
        try {
            jrReporte= (JasperReport)JRLoader.loadObject(
            getClass().getClassLoader().getResource("Reportes/ReportesCompra.jasper")
            );
            
            Map params = new HashMap();
            params.put("NombreCliente", "Dayana");
            params.put("NombreProducto", "Lenteja");
            
            JasperPrint jpReporte = JasperFillManager.fillReport(jrReporte, params,ConexionDB.conexion);
            JasperViewer jReporteViewer = new JasperViewer(jpReporte,false);
            jReporteViewer.setVisible(true);
            
        } catch (JRException e) {
            System.out.println("");
        }
       
    }//GEN-LAST:event_BTNReporteCompraActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscarCompra;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton BTNLimpiar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JButton BTNReporteCompra;
    private javax.swing.JComboBox<Cliente> CBOCliente;
    private javax.swing.JComboBox<Producto> CBOProducto;
    private javax.swing.JTable TBLCompra;
    private javax.swing.JTextField TXTBuscarCompra;
    private javax.swing.JFormattedTextField TXTIdCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void llenarComboCliente()
    {
    Cliente unCliente = new Cliente();
    Iterator<Cliente> itCliente = unCliente.listar();
    CBOCliente.removeAllItems();
    Cliente seleccione = new Cliente();
    seleccione.setNombreCliente("seleccione cliente");
    CBOCliente.addItem(seleccione);
        while (itCliente.hasNext()) {            
            CBOCliente.addItem(itCliente.next());
        }
    }
    
    //LLENAR EL COMBO DE PRODUCTO
    
    private void llenarComboProducto()
    {
        Producto unProducto = new Producto();
    Iterator<Producto> itProducto = unProducto.listar();
    CBOProducto.removeAllItems();
    Producto seleccionar = new Producto();
    seleccionar.setNombreProducto("seleccione producto");
    CBOProducto.addItem(seleccionar);
        while (itProducto.hasNext()) {            
            CBOProducto.addItem(itProducto.next());
        }
    }
     
    
    
    //OBTENER LA COMPRA
    
    private Compra obtenerCompra()
    {
    
    Compra laCompra = new Compra();
    laCompra.setIdCompra((Integer)TXTIdCompra.getValue());
    laCompra.setIdClienteCompra(((Cliente)CBOCliente.getSelectedItem()).getId());
    laCompra.setIdProductoCompra(((Producto)CBOProducto.getSelectedItem()).getIdProducto());
      
    return laCompra;
    }
    
    //ESTO ES PARA LIMPIAR EL MKFORMULARIO
     private void limpiarFormulario()
     {
     CBOCliente.getSelectedItem();
     CBOProducto.getSelectedItem();
     BTNEliminar.setEnabled(false);
     BTNModificar.setEnabled(false);
     llenarTabla();
     }

     //Llenar tabla
     
     public void llenarTabla()
     {
     Compra unaCompra = new Compra();
     DefaultTableModel tabla = ( DefaultTableModel)TBLCompra.getModel();
       Iterator<Compra> itCompra = unaCompra.listar();//listado de clientes
        Object[] filaCompra = new Object[TBLCompra.getColumnCount()];//unafila
        tabla.setRowCount(0);
         while (itCompra.hasNext()) {             
             unaCompra = itCompra.next();
             filaCompra[0]= unaCompra.getIdCompra();
            filaCompra[1] = new Cliente().buscarPorId(unaCompra.getIdClienteCompra());
            filaCompra[2] = new Producto().buscarPorId(unaCompra.getIdProductoCompra());
             tabla.addRow(filaCompra);
         }
        
     }
     
     
     //LLENAR LA TABLA CON LA BUSQUEDA
     private void llenarTablaConBusqueda(String busqueda)
     {
      Compra unaCompra = new Compra();
     DefaultTableModel tabla = ( DefaultTableModel)TBLCompra.getModel();
       Iterator<Compra> itCompra = unaCompra.buscar(busqueda);//listado de clientes
        Object[] filaCompra= new Object[TBLCompra.getColumnCount()];//unafila
        tabla.setRowCount(0);
         while (itCompra.hasNext()) {             
             unaCompra = itCompra.next();
             filaCompra[0]= unaCompra.getIdCompra();
              filaCompra[1]= new Cliente().buscarPorId(unaCompra.getIdClienteCompra());
              filaCompra[2] = new Producto().buscarPorId(unaCompra.getIdProductoCompra());
               ((DefaultTableModel)TBLCompra.getModel()).addRow(filaCompra);
         }
        
     }
      
     
}
