/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorPedido;
import Modelo.ConexionDB;
import Modelo.Pedido;
import Modelo.Producto;
import Modelo.Proveedor;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Duvan
 */
public class FRMPedido extends javax.swing.JInternalFrame {

   ControladorPedido pedidoController = new ControladorPedido();
   
    public FRMPedido() {
        initComponents();
        TXTIdPedido.setValue(0);
        TXTIdPedido.setVisible(false);
        llenarTabla();
        llenarComboProveedor();
        llenarComboProducto();
        limpiarFormulario();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CBOProveedor = new javax.swing.JComboBox<Proveedor>();
        CBOProducto = new javax.swing.JComboBox<Producto>();
        TXTObservacionPedido = new javax.swing.JTextField();
        TXTIdPedido = new javax.swing.JFormattedTextField();
        TXTBuscarPedido = new javax.swing.JTextField();
        BTNBuscarPedido = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLPedido = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BTNInsertar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNLimpiar = new javax.swing.JButton();
        BTNCerrar = new javax.swing.JButton();
        BTNReportePedido = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Pedidos");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLene Los Datos"));

        jLabel1.setText("Proveedor");

        jLabel2.setText("Producto");

        jLabel3.setText("Observacion");

        CBOProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CBOProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TXTBuscarPedido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarPedidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarPedidoFocusLost(evt);
            }
        });

        BTNBuscarPedido.setText("Buscar");
        BTNBuscarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarPedidoActionPerformed(evt);
            }
        });

        jLabel4.setText("Buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBOProveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CBOProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TXTIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TXTBuscarPedido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TXTObservacionPedido))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TXTIdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CBOProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBOProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTObservacionPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTBuscarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BTNBuscarPedido))
                .addGap(17, 17, 17))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        TBLPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "             Proveedor", "            Producto", "           Observación", "           Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLPedido.setToolTipText("");
        TBLPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLPedido);
        if (TBLPedido.getColumnModel().getColumnCount() > 0) {
            TBLPedido.getColumnModel().getColumn(0).setMinWidth(40);
            TBLPedido.getColumnModel().getColumn(0).setPreferredWidth(40);
            TBLPedido.getColumnModel().getColumn(0).setMaxWidth(40);
            TBLPedido.getColumnModel().getColumn(1).setMinWidth(211);
            TBLPedido.getColumnModel().getColumn(1).setPreferredWidth(211);
            TBLPedido.getColumnModel().getColumn(1).setMaxWidth(211);
            TBLPedido.getColumnModel().getColumn(2).setMinWidth(211);
            TBLPedido.getColumnModel().getColumn(2).setPreferredWidth(211);
            TBLPedido.getColumnModel().getColumn(2).setMaxWidth(211);
            TBLPedido.getColumnModel().getColumn(4).setMinWidth(180);
            TBLPedido.getColumnModel().getColumn(4).setPreferredWidth(180);
            TBLPedido.getColumnModel().getColumn(4).setMaxWidth(180);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Operaciones"));

        BTNInsertar.setBackground(new java.awt.Color(51, 255, 51));
        BTNInsertar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNInsertar.setText("Guardar");
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });

        BTNModificar.setBackground(new java.awt.Color(51, 255, 255));
        BTNModificar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BTNEliminar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        BTNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNLimpiar.setText("Limpiar");
        BTNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarActionPerformed(evt);
            }
        });

        BTNCerrar.setBackground(new java.awt.Color(102, 102, 102));
        BTNCerrar.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        BTNReportePedido.setBackground(new java.awt.Color(204, 0, 204));
        BTNReportePedido.setFont(new java.awt.Font("Cambria", 3, 12)); // NOI18N
        BTNReportePedido.setText("Reporte");
        BTNReportePedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReportePedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTNLimpiar)
                .addGap(9, 9, 9))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(BTNReportePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTNLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(BTNModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTNEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTNCerrar)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BTNReportePedido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TBLPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLPedidoMouseClicked
       if (evt.getClickCount()==1) {
            int fila = TBLPedido.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                TXTIdPedido.setValue((Integer)  TBLPedido.getValueAt(fila, 0));
                CBOProveedor.setSelectedItem((Proveedor)TBLPedido.getValueAt(fila, 1));
                CBOProducto.setSelectedItem((Producto)TBLPedido.getValueAt(fila, 2));
                TXTObservacionPedido.setText((String)TBLPedido.getValueAt(fila, 3));
                BTNEliminar.setEnabled(true);
                BTNModificar.setEnabled(true);
             
            }
        }
    }//GEN-LAST:event_TBLPedidoMouseClicked

    private void TXTBuscarPedidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarPedidoFocusGained
        if (TXTBuscarPedido.getText().equals("Escriba texto a buscar")) {
            TXTBuscarPedido.setText("");
                    
        }
    }//GEN-LAST:event_TXTBuscarPedidoFocusGained

    private void TXTBuscarPedidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarPedidoFocusLost
        if (TXTBuscarPedido.getText().isEmpty()) {
            TXTBuscarPedido.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarPedidoFocusLost

    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        pedidoController.controlarAccion(evt,obtenerPedido());
        limpiarFormulario();
    }//GEN-LAST:event_BTNInsertarActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
        pedidoController.controlarAccion(evt,obtenerPedido());
        limpiarFormulario();
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
       pedidoController.controlarAccion(evt,obtenerPedido());
        limpiarFormulario();
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarActionPerformed
      
        limpiarFormulario();
    }//GEN-LAST:event_BTNLimpiarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void BTNBuscarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarPedidoActionPerformed
        llenarTablaConBusqueda(TXTBuscarPedido.getText());
    }//GEN-LAST:event_BTNBuscarPedidoActionPerformed

    private void BTNReportePedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReportePedidoActionPerformed
       JasperReport jrReporte = null;
       
        try {
            jrReporte=(JasperReport)JRLoader.loadObject(
            getClass().getClassLoader().getResource("Reportes/ReporteDeAseo.jasper")
            );
            
            Map params = new HashMap();
            JasperPrint jpReporte = JasperFillManager.fillReport(jrReporte, params,ConexionDB.conexion);
            JasperViewer jReporteViewer = new JasperViewer(jpReporte,false);
            jReporteViewer.setVisible(true);
        } catch (JRException e) {
            System.out.println("error en jasper que creo no se podra solucionar  "+e.getMessage());
                    
        }
    }//GEN-LAST:event_BTNReportePedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscarPedido;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton BTNLimpiar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JButton BTNReportePedido;
    private javax.swing.JComboBox<Producto> CBOProducto;
    private javax.swing.JComboBox<Proveedor> CBOProveedor;
    private javax.swing.JTable TBLPedido;
    private javax.swing.JTextField TXTBuscarPedido;
    private javax.swing.JFormattedTextField TXTIdPedido;
    private javax.swing.JTextField TXTObservacionPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

private void llenarComboProveedor()
{
    Proveedor unProveedor = new Proveedor();
    Iterator<Proveedor> itProveedor = unProveedor.listar();
    CBOProveedor.removeAllItems();
    Proveedor seleccionar = new Proveedor();
    seleccionar.setNombreProveedor("sellecione Proveedor");
    CBOProveedor.addItem(seleccionar);
    while (itProveedor.hasNext()) {        
        CBOProveedor.addItem(itProveedor.next());
    }
            
}

private void llenarComboProducto()
{
Producto unProducto = new Producto();
Iterator<Producto> itProducto = unProducto.listar();
CBOProducto.removeAllItems();
Producto seleccionar = new Producto();
seleccionar.setNombreProducto("seleccione Producto");
CBOProducto.addItem(seleccionar);
    while (itProducto.hasNext()) {        
        CBOProducto.addItem(itProducto.next());
    }
}

//OBTENER PEDIDO
private Pedido obtenerPedido()
{
Pedido elPedido = new Pedido();
elPedido.setIdPedido((Integer)TXTIdPedido.getValue());
elPedido.setIdProveedorPedido(((Proveedor)CBOProveedor.getSelectedItem()).getIdProveedor());
elPedido.setIdProductoPedido(((Producto)CBOProducto.getSelectedItem()).getIdProducto());
elPedido.setObservacionPedido(TXTObservacionPedido.getText());      
return elPedido;
}

//LLENAR TABLA
  
public void llenarTabla()
{ 
    Pedido unPedido = new Pedido();
     DefaultTableModel tabla = ( DefaultTableModel)TBLPedido.getModel();
     Iterator<Pedido> itPedido = unPedido.listar();
     Object[] filaPedido = new Object[TBLPedido.getColumnCount()];
     tabla.setRowCount(0);
     while (itPedido.hasNext()) {        
        unPedido = itPedido.next();
        filaPedido[0]= unPedido.getIdPedido();
        filaPedido[1] = new Proveedor().buscarPorId(unPedido.getIdProveedorPedido());
        filaPedido[2] = new Producto().buscarPorId(unPedido.getIdProductoPedido());
        filaPedido[3] = unPedido.getObservacionPedido();
        filaPedido[4] = unPedido.getFechaPedido();
        
        tabla.addRow(filaPedido);
         
    }
}
//LLENAR TABLA CON BUSQUEDA

private void llenarTablaConBusqueda(String busqueda)
{
Pedido unPedido = new Pedido();
     DefaultTableModel tabla = ( DefaultTableModel)TBLPedido.getModel();
     Iterator<Pedido> itPedido = unPedido.buscar(busqueda);
     Object[] filaPedido = new Object[TBLPedido.getColumnCount()];
     tabla.setRowCount(0);
     while (itPedido.hasNext()) {        
        unPedido = itPedido.next();
        filaPedido[0]= unPedido.getIdPedido();
        filaPedido[1] = new Proveedor().buscarPorId(unPedido.getIdProveedorPedido());
        filaPedido[2] = new Producto().buscarPorId(unPedido.getIdProductoPedido());
        filaPedido[3] = unPedido.getObservacionPedido();
        filaPedido[4] = unPedido.getFechaPedido();
       
        ((DefaultTableModel)TBLPedido.getModel()).addRow(filaPedido);
}
}
//LIMPIAR FORMULARIO
private void limpiarFormulario()
{
TXTObservacionPedido.setText("");
BTNEliminar.setEnabled(false);
BTNModificar.setEnabled(false);
llenarTabla();
}
//esta llave no se puede borrar
}
