/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorProveedor;
import Modelo.Proveedor;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Duvan
 */
public class FRMProveedor extends javax.swing.JInternalFrame {

    ControladorProveedor proveedorController = new ControladorProveedor();
    public FRMProveedor() {
        initComponents();
        TXTIdProveedor.setValue(0);
        TXTIdProveedor.setVisible(false);
        limpiarFormulario();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TXTNombreProveedor = new javax.swing.JTextField();
        TXTRUTProveedor = new javax.swing.JTextField();
        TXTTelefonoProveedor = new javax.swing.JTextField();
        TXTDireccionProveedor = new javax.swing.JTextField();
        TXTBuscarProveedor = new javax.swing.JTextField();
        BTNBuscarProveedor = new javax.swing.JButton();
        TXTIdProveedor = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLProveedor = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BTNInsertar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNLimpiar = new javax.swing.JButton();
        BTNCerrar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLene Los Datos"));

        jLabel1.setText("Nombre");

        jLabel2.setText("RUT");

        jLabel3.setText("Telefono");

        jLabel4.setText("Direccion");

        jLabel5.setText("Buscar");

        TXTDireccionProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXTDireccionProveedorActionPerformed(evt);
            }
        });

        TXTBuscarProveedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarProveedorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarProveedorFocusLost(evt);
            }
        });

        BTNBuscarProveedor.setText("Buscar");
        BTNBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TXTNombreProveedor)
                    .addComponent(TXTRUTProveedor)
                    .addComponent(TXTTelefonoProveedor)
                    .addComponent(TXTDireccionProveedor)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TXTBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNBuscarProveedor)))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TXTIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TXTIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TXTRUTProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TXTTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TXTDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscarProveedor))
                .addGap(15, 15, 15))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TBLProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "RUT", "Telefono", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLProveedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLProveedor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acciones"));

        BTNInsertar.setBackground(new java.awt.Color(51, 255, 0));
        BTNInsertar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNInsertar.setText("Guardar");
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });

        BTNModificar.setBackground(new java.awt.Color(0, 255, 255));
        BTNModificar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(255, 0, 51));
        BTNEliminar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        BTNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNLimpiar.setText("Limpiar");
        BTNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarActionPerformed(evt);
            }
        });

        BTNCerrar.setBackground(new java.awt.Color(102, 102, 102));
        BTNCerrar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXTDireccionProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXTDireccionProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXTDireccionProveedorActionPerformed

    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        proveedorController.controlarAccion(evt, obtenerProveedor());
        llenarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_BTNInsertarActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
         proveedorController.controlarAccion(evt, obtenerProveedor());
        llenarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        proveedorController.controlarAccion(evt, obtenerProveedor());
        llenarTabla();
        limpiarFormulario();
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarActionPerformed
       limpiarFormulario();
    }//GEN-LAST:event_BTNLimpiarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
       doDefaultCloseAction();
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void TBLProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLProveedorMouseClicked
        if (evt.getClickCount()==1) {
            int fila = TBLProveedor.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                TXTIdProveedor.setValue((Integer)  TBLProveedor.getValueAt(fila, 0));
                TXTNombreProveedor.setText((String)  TBLProveedor.getValueAt(fila, 1));
                TXTRUTProveedor.setText((String)  TBLProveedor.getValueAt(fila, 2));
                TXTTelefonoProveedor.setText((String)  TBLProveedor.getValueAt(fila, 3));
                TXTDireccionProveedor.setText((String)  TBLProveedor.getValueAt(fila, 4));
                BTNEliminar.setEnabled(true);
                BTNModificar.setEnabled(true);
               
                
            }
            
        }
    }//GEN-LAST:event_TBLProveedorMouseClicked

    private void TXTBuscarProveedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarProveedorFocusGained
        if (TXTBuscarProveedor.getText().equals("Escriba texto a buscar") ){
            TXTBuscarProveedor.setText("");
            
        }
    }//GEN-LAST:event_TXTBuscarProveedorFocusGained

    private void TXTBuscarProveedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarProveedorFocusLost
        if (TXTBuscarProveedor.getText().isEmpty()) {
            TXTBuscarProveedor.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarProveedorFocusLost

    private void BTNBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarProveedorActionPerformed
        llenarTablaConBusqueda(TXTBuscarProveedor.getText());
    }//GEN-LAST:event_BTNBuscarProveedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscarProveedor;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton BTNLimpiar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JTable TBLProveedor;
    private javax.swing.JTextField TXTBuscarProveedor;
    private javax.swing.JTextField TXTDireccionProveedor;
    private javax.swing.JFormattedTextField TXTIdProveedor;
    private javax.swing.JTextField TXTNombreProveedor;
    private javax.swing.JTextField TXTRUTProveedor;
    private javax.swing.JTextField TXTTelefonoProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

//LIMPIAR FORMULARIO
    
    private void limpiarFormulario()
    {
    TXTIdProveedor.setValue(0);
    TXTNombreProveedor.setText("");
    TXTRUTProveedor.setText("");
    TXTDireccionProveedor.setText("");
    TXTTelefonoProveedor.setText((""));
    BTNModificar.setEnabled(false);
    BTNEliminar.setEnabled(false);
    llenarTabla();
    }
    
//LLENAR TABLA
 public void llenarTabla()
 {
 Proveedor unProveedor = new Proveedor();
 DefaultTableModel tabla = (DefaultTableModel) TBLProveedor.getModel();
 Iterator<Proveedor> itProveedor = unProveedor.listar();
 Object[] filaProveedor = new Object[TBLProveedor.getColumnCount()];
 tabla.setRowCount(0);
     while (itProveedor.hasNext()) {         
         unProveedor = itProveedor.next();
         filaProveedor[0] = unProveedor.getIdProveedor();
         filaProveedor[1] = unProveedor.getNombreProveedor();
         filaProveedor[2] = unProveedor.getRUTProveedor();
         filaProveedor[3] = unProveedor.getTelefonoProveedor();
         filaProveedor[4] = unProveedor.getDireccionProveedor();
         tabla.addRow(filaProveedor);
                 
     }
 
 }
 
 //LLENAR TABLA CON BUSQUEDA
 private void llenarTablaConBusqueda(String busqueda)
 {
 Proveedor unProveedor = new Proveedor();
 DefaultTableModel tabla = (DefaultTableModel) TBLProveedor.getModel();
 Iterator<Proveedor> itProveedor = unProveedor.buscar(busqueda);
 Object[] filaProveedor = new Object[TBLProveedor.getColumnCount()];
 tabla.setRowCount(0);
     while (itProveedor.hasNext()) {         
         unProveedor = itProveedor.next();
         filaProveedor[0] = unProveedor.getIdProveedor();
         filaProveedor[1] = unProveedor.getNombreProveedor();
         filaProveedor[2] = unProveedor.getRUTProveedor();
         filaProveedor[3] = unProveedor.getTelefonoProveedor();
         filaProveedor[4] = unProveedor.getDireccionProveedor();
          ((DefaultTableModel)TBLProveedor.getModel()).addRow(filaProveedor);
 }
}
 
 //OBTENER PROVEEDOR
   private Proveedor obtenerProveedor()
   {
       String nombre,rut,tel,dir;
       nombre = TXTNombreProveedor.getText();
       rut = TXTRUTProveedor.getText();
       tel = TXTTelefonoProveedor.getText();
       dir = TXTDireccionProveedor.getText();
       System.out.println(""+nombre+rut+tel+dir);
       
       Proveedor elProveedor = new Proveedor();
       elProveedor.setIdProveedor((Integer)TXTIdProveedor.getValue());
       elProveedor.setNombreProveedor(TXTNombreProveedor.getText());
       elProveedor.setRUTProveedor(TXTRUTProveedor.getText());
       elProveedor.setTelefonoProveedor(TXTTelefonoProveedor.getText());
       elProveedor.setDireccionProveedor(TXTDireccionProveedor.getText());
       return elProveedor;
       
   }
          
 
 
}

