/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.ControladorProducto;
import Modelo.ConexionDB;
import Modelo.Producto;
import Modelo.Proveedor;
import Modelo.Tipo;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Duvan
 */
public class FRMProducto extends javax.swing.JInternalFrame {

   ControladorProducto productoController = new ControladorProducto();
    public FRMProducto() {
        initComponents();
        limpiarFormulario();
        TXTIdProducto.setValue(0);
        TXTIdProducto.setVisible(false);
        llenarComboProveedor();
        llenarComboTipo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TXTIdProducto = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TXTNombreProducto = new javax.swing.JTextField();
        TXTPesoProducto = new javax.swing.JFormattedTextField();
        CBOProveedorProducto = new javax.swing.JComboBox<Proveedor>();
        TXTPrecioProducto = new javax.swing.JFormattedTextField();
        TXTBuscarProducto = new javax.swing.JTextField();
        BTNBuscarProducto = new javax.swing.JButton();
        CBOTipoProducto = new javax.swing.JComboBox<Tipo>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        BTNInsertar = new javax.swing.JButton();
        BTNModificar = new javax.swing.JButton();
        BTNEliminar = new javax.swing.JButton();
        BTNLimpiar = new javax.swing.JButton();
        BTNCerrar = new javax.swing.JButton();
        BTNReporteProducto = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Formulario Producto");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLene Los Datos"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Peso");

        jLabel3.setText("Proveedor");

        jLabel4.setText("Tipo");

        jLabel5.setText("Precio");

        jLabel6.setText("Buscar");

        CBOProveedorProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TXTBuscarProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TXTBuscarProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TXTBuscarProductoFocusLost(evt);
            }
        });

        BTNBuscarProducto.setText("Buscar");
        BTNBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarProductoActionPerformed(evt);
            }
        });

        CBOTipoProducto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBOTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOTipoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TXTIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TXTBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNBuscarProducto))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CBOTipoProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, 292, Short.MAX_VALUE)
                        .addComponent(TXTNombreProducto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(TXTPesoProducto, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(CBOProveedorProducto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TXTPrecioProducto, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(TXTIdProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(TXTNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addComponent(TXTPesoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBOProveedorProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CBOTipoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TXTPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TXTBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscarProducto))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TBLProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Peso en g.", "Proveedor", "Tipo", "Precio $"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TBLProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TBLProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TBLProducto);
        if (TBLProducto.getColumnModel().getColumnCount() > 0) {
            TBLProducto.getColumnModel().getColumn(0).setMinWidth(30);
            TBLProducto.getColumnModel().getColumn(0).setPreferredWidth(30);
            TBLProducto.getColumnModel().getColumn(0).setMaxWidth(30);
            TBLProducto.getColumnModel().getColumn(2).setMinWidth(70);
            TBLProducto.getColumnModel().getColumn(2).setPreferredWidth(70);
            TBLProducto.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acciones"));

        BTNInsertar.setBackground(new java.awt.Color(51, 255, 51));
        BTNInsertar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNInsertar.setText("Guardar");
        BTNInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNInsertarActionPerformed(evt);
            }
        });

        BTNModificar.setBackground(new java.awt.Color(0, 255, 255));
        BTNModificar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNModificar.setText("Modificar");
        BTNModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNModificarActionPerformed(evt);
            }
        });

        BTNEliminar.setBackground(new java.awt.Color(255, 0, 0));
        BTNEliminar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNEliminar.setText("Eliminar");
        BTNEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNEliminarActionPerformed(evt);
            }
        });

        BTNLimpiar.setBackground(new java.awt.Color(255, 255, 255));
        BTNLimpiar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNLimpiar.setText("Limpiar");
        BTNLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNLimpiarActionPerformed(evt);
            }
        });

        BTNCerrar.setBackground(new java.awt.Color(153, 153, 153));
        BTNCerrar.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNCerrar.setText("Cerrar");
        BTNCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCerrarActionPerformed(evt);
            }
        });

        BTNReporteProducto.setBackground(new java.awt.Color(153, 0, 153));
        BTNReporteProducto.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        BTNReporteProducto.setText("Generar Reporte");
        BTNReporteProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNReporteProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTNModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BTNEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTNLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(BTNReporteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTNEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BTNInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BTNLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNReporteProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNInsertarActionPerformed
        productoController.controlarAccion(evt, obtenerProducto());
        llenarTabla();
    }//GEN-LAST:event_BTNInsertarActionPerformed

    private void BTNModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNModificarActionPerformed
      productoController.controlarAccion(evt, obtenerProducto());
        llenarTabla();
    }//GEN-LAST:event_BTNModificarActionPerformed

    private void BTNEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNEliminarActionPerformed
        productoController.controlarAccion(evt, obtenerProducto());
        llenarTabla();
    }//GEN-LAST:event_BTNEliminarActionPerformed

    private void BTNLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNLimpiarActionPerformed
       limpiarFormulario();
    }//GEN-LAST:event_BTNLimpiarActionPerformed

    private void BTNCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCerrarActionPerformed
        doDefaultCloseAction();
    }//GEN-LAST:event_BTNCerrarActionPerformed

    private void TBLProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TBLProductoMouseClicked
        if (evt.getClickCount()==2) {
            int fila = TBLProducto.rowAtPoint(evt.getPoint());
            if (fila>-1) {
                TXTIdProducto.setValue(   (Integer)TBLProducto.getValueAt(fila, 0));
                TXTNombreProducto.setText((String)TBLProducto.getValueAt(fila, 1));
                TXTPesoProducto.setValue((Integer)TBLProducto.getValueAt(fila, 2));
                CBOProveedorProducto.setSelectedItem((Proveedor)TBLProducto.getValueAt(fila, 3));
                CBOTipoProducto.setSelectedItem((Tipo)TBLProducto.getValueAt(fila, 4));
                TXTPrecioProducto.setValue((Integer)TBLProducto.getValueAt(fila, 5));
                 BTNEliminar.setEnabled(true);
                BTNModificar.setEnabled(true);
            }
        }
        
        
    }//GEN-LAST:event_TBLProductoMouseClicked

    private void BTNBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarProductoActionPerformed
        llenarTablaConBusqueda(TXTBuscarProducto.getText());
    }//GEN-LAST:event_BTNBuscarProductoActionPerformed

    private void TXTBuscarProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarProductoFocusGained
        if (TXTBuscarProducto.getText().equals("Escriba texto a buscar")) {
            TXTBuscarProducto.setText("");
        }
    }//GEN-LAST:event_TXTBuscarProductoFocusGained

    private void TXTBuscarProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TXTBuscarProductoFocusLost
        if (TXTBuscarProducto.getText().isEmpty()) {
             TXTBuscarProducto.setText("Escriba texto a buscar");
        }
    }//GEN-LAST:event_TXTBuscarProductoFocusLost

    private void CBOTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOTipoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOTipoProductoActionPerformed

    private void BTNReporteProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNReporteProductoActionPerformed
       JasperReport jrReporte = null;
        try {
            jrReporte = (JasperReport)JRLoader.loadObject(getClass().getClassLoader().getResource("Reportes/ReportesProyecto.jasper"));
            Map params = new HashMap();
            params.put("TipoDeProducto", "Seco");
            JasperPrint jpReporte = JasperFillManager.fillReport(jrReporte, params,ConexionDB.conexion);
            JasperViewer jReporteViewer = new JasperViewer(jpReporte,false);
            jReporteViewer.setVisible(true);
            System.out.println("se ha creado un reporte");
        } catch (JRException e) {
            System.out.println("error en el Jasper que no vas a poder solucionar"+e.getMessage());
        }
    }//GEN-LAST:event_BTNReporteProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscarProducto;
    private javax.swing.JButton BTNCerrar;
    private javax.swing.JButton BTNEliminar;
    private javax.swing.JButton BTNInsertar;
    private javax.swing.JButton BTNLimpiar;
    private javax.swing.JButton BTNModificar;
    private javax.swing.JButton BTNReporteProducto;
    private javax.swing.JComboBox<Proveedor> CBOProveedorProducto;
    private javax.swing.JComboBox<Tipo> CBOTipoProducto;
    private javax.swing.JTable TBLProducto;
    private javax.swing.JTextField TXTBuscarProducto;
    private javax.swing.JFormattedTextField TXTIdProducto;
    private javax.swing.JTextField TXTNombreProducto;
    private javax.swing.JFormattedTextField TXTPesoProducto;
    private javax.swing.JFormattedTextField TXTPrecioProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
        
        //LLENAR EL COMBO PROVEEDOR
       private void llenarComboProveedor()
       {
      Proveedor unProveedor = new Proveedor();
      Iterator<Proveedor> itProveedor = unProveedor.listar();
      CBOProveedorProducto.removeAllItems();
      Proveedor seleccionar = new Proveedor();
      seleccionar.setNombreProveedor("seleccione Proveedor");
      CBOProveedorProducto.addItem(seleccionar);
           while (itProveedor.hasNext()) {
              CBOProveedorProducto.addItem(itProveedor.next());
           }
       }
       
       //LLENAR COMBO TIPO
       
       private void llenarComboTipo()
       {
       Tipo unTipo = new Tipo();
       Iterator<Tipo> itTipo = unTipo.listar();
       CBOTipoProducto.removeAllItems();
       Tipo seleccionar = new Tipo();
       seleccionar.setDescripcionTipo("seleccione Tipo");
       CBOTipoProducto.addItem(seleccionar);
           while (itTipo.hasNext()) {
              CBOTipoProducto.addItem(itTipo.next());
           }
       }
       
       //LIMPIAR EL FORMULARIO
       
       private void limpiarFormulario()
       {
       TXTIdProducto.setValue(0);
       TXTNombreProducto.setText("");
       TXTPesoProducto.setValue(0);
       TXTPrecioProducto.setValue(0);
       BTNModificar.setEnabled(false);
       BTNEliminar.setEnabled(false);
       llenarTabla();
       llenarComboProveedor();
       llenarComboTipo();
       }
       
       //LLENAR TABLA
       
       public void llenarTabla()
       {
       Producto unProducto = new Producto();
       DefaultTableModel tabla = (DefaultTableModel)TBLProducto.getModel();
       Iterator<Producto> itProducto = unProducto.listar();
       Object[] filaProducto = new Object[TBLProducto.getColumnCount()];
       tabla.setRowCount(0);//limpiar la tabla y ya
           while (itProducto.hasNext()) {
              unProducto = itProducto.next();
              filaProducto[0] = unProducto.getIdProducto();
              filaProducto[1] = unProducto.getNombreProducto();
              filaProducto[2] = unProducto.getPesoProducto();
              filaProducto[3] = new Proveedor().buscarPorId(unProducto.getIdProveedor_Producto());
              filaProducto[4] = new Tipo().buscarPorId(unProducto.getIdTipo_Producto());
              filaProducto[5] = unProducto.getPrecioProducto();
              tabla.addRow(filaProducto);
           }
       }
       
       //LLENAR TABLA CON BUSQUEDAD
       
       private void llenarTablaConBusqueda(String busqueda)
       {
        Producto unProducto = new Producto();
       DefaultTableModel tabla = (DefaultTableModel)TBLProducto.getModel();
       Iterator<Producto> itProducto = unProducto.buscar(busqueda);
       Object[] filaProducto = new Object[TBLProducto.getColumnCount()];
       tabla.setRowCount(0);//limpiar la tabla y ya
           while (itProducto.hasNext()) {
              unProducto = itProducto.next();
              filaProducto[0] = unProducto.getIdProducto();
              filaProducto[1] = unProducto.getNombreProducto();
              filaProducto[2] = unProducto.getPesoProducto();
              filaProducto[3] = new Proveedor().buscarPorId(unProducto.getIdProveedor_Producto());
              filaProducto[4] = new Tipo().buscarPorId(unProducto.getIdTipo_Producto());
              filaProducto[5] = unProducto.getPrecioProducto();
              ((DefaultTableModel)TBLProducto.getModel()).addRow(filaProducto);  
           }
       
       }
       
       //OBTENER EL PRODUCTO
       
       private Producto obtenerProducto()
       {
       Producto elProducto = new Producto();
       elProducto.setIdProducto((Integer)TXTIdProducto.getValue());
       elProducto.setNombreProducto(TXTNombreProducto.getText());
       elProducto.setPesoProducto((Integer)TXTPesoProducto.getValue());
       elProducto.setIdProveedor_Producto(((Proveedor)CBOProveedorProducto.getSelectedItem()).getIdProveedor());
       elProducto.setIdTipo_Producto(((Tipo)CBOTipoProducto.getSelectedItem()).getIdTipo());
       elProducto.setPrecioProducto(  (Integer)TXTPrecioProducto.getValue());
       return elProducto;
       }
       
       
     //esta llave no se puede eliminar
}
