/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Modelo.ConexionDB;
import java.beans.PropertyVetoException;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Duvan
 */
public class MDISistemaCliente extends javax.swing.JFrame {

    FRMCliente FormularioCliente;
    FRMProducto FormularioProducto;
    FRMProveedor FormularioProveedor;
    FRMEmpleado FormularioEmpleado;
    FRMCompra FormularioCompra;
    FRMUsuario FormularioUsuario;
    FRMAuditoria FormularioAuditoria;
    FRMPedido FormularioPedido;
    FRMBodega FormularioBodega;
    FRMTipoProducto FormularioTipo;
    FRMLogin FormularioLogin;
    
    
    public MDISistemaCliente() {
        ConexionDB.getInstance();
        initComponents();
        
       
       FormularioCliente = new FRMCliente();
       FormularioProducto = new FRMProducto();
       FormularioProveedor = new FRMProveedor();
       FormularioEmpleado = new FRMEmpleado();
       FormularioCompra = new FRMCompra();
       FormularioUsuario = new FRMUsuario();
       FormularioAuditoria = new FRMAuditoria();
       FormularioPedido = new FRMPedido();
       FormularioBodega = new FRMBodega();
       FormularioTipo = new FRMTipoProducto();
       FormularioLogin = new FRMLogin();
       
        
        //aca se añaden los formularios al mdi
        
        escritorio.add(FormularioCliente);
        escritorio.add(FormularioProducto);
        escritorio.add(FormularioProveedor);
        escritorio.add(FormularioEmpleado);
        escritorio.add(FormularioCompra);
        escritorio.add(FormularioUsuario);
        escritorio.add(FormularioAuditoria);
        escritorio.add(FormularioPedido);
        escritorio.add(FormularioBodega);
        escritorio.add(FormularioTipo);
        escritorio.add(FormularioLogin);
        
        FormularioLogin.setVisible(true);
        FormularioLogin.setLocation(150, 70);
                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        MNUAdministrar = new javax.swing.JMenuBar();
        itemBodega = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        itemAuditoria = new javax.swing.JCheckBoxMenuItem();
        itemmBodega = new javax.swing.JCheckBoxMenuItem();
        itemCliente = new javax.swing.JCheckBoxMenuItem();
        itemCompra = new javax.swing.JCheckBoxMenuItem();
        itemEmpleado = new javax.swing.JCheckBoxMenuItem();
        itemPedido = new javax.swing.JCheckBoxMenuItem();
        itemProducto = new javax.swing.JCheckBoxMenuItem();
        itemProveedor = new javax.swing.JCheckBoxMenuItem();
        itemTipoProducto = new javax.swing.JCheckBoxMenuItem();
        itemUsuario = new javax.swing.JCheckBoxMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(51, 51, 255));
        escritorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                escritorioMouseClicked(evt);
            }
        });

        itemBodega.setMnemonic('f');
        itemBodega.setText("    Administrar   ");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        itemBodega.add(openMenuItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        itemBodega.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        itemBodega.add(saveAsMenuItem);

        itemAuditoria.setSelected(true);
        itemAuditoria.setText("Auditoria");
        itemAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAuditoriaActionPerformed(evt);
            }
        });
        itemBodega.add(itemAuditoria);

        itemmBodega.setSelected(true);
        itemmBodega.setText("Bodega");
        itemmBodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemmBodegaActionPerformed(evt);
            }
        });
        itemBodega.add(itemmBodega);

        itemCliente.setSelected(true);
        itemCliente.setText("Cliente");
        itemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemClienteActionPerformed(evt);
            }
        });
        itemBodega.add(itemCliente);

        itemCompra.setSelected(true);
        itemCompra.setText("Compra");
        itemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraActionPerformed(evt);
            }
        });
        itemBodega.add(itemCompra);

        itemEmpleado.setSelected(true);
        itemEmpleado.setText("Empleado");
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        itemBodega.add(itemEmpleado);

        itemPedido.setSelected(true);
        itemPedido.setText("Pedido");
        itemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPedidoActionPerformed(evt);
            }
        });
        itemBodega.add(itemPedido);

        itemProducto.setSelected(true);
        itemProducto.setText("Producto");
        itemProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProductoActionPerformed(evt);
            }
        });
        itemBodega.add(itemProducto);

        itemProveedor.setSelected(true);
        itemProveedor.setText("Proveedor");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        itemBodega.add(itemProveedor);

        itemTipoProducto.setSelected(true);
        itemTipoProducto.setText("Tipo Producto");
        itemTipoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipoProductoActionPerformed(evt);
            }
        });
        itemBodega.add(itemTipoProducto);

        itemUsuario.setSelected(true);
        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        itemBodega.add(itemUsuario);

        itemSalir.setMnemonic('x');
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        itemBodega.add(itemSalir);

        MNUAdministrar.add(itemBodega);

        editMenu.setMnemonic('e');
        editMenu.setText("Editar");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        MNUAdministrar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ayuda");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        MNUAdministrar.add(helpMenu);

        setJMenuBar(MNUAdministrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
       ConexionDB.desconectar();
        try {
            FormularioCliente.setClosed(true);
            FormularioProducto.setClosed(true);
            FormularioProveedor.setClosed(true);
            FormularioEmpleado.setClosed(true);
            FormularioCompra.setClosed(true);
            FormularioUsuario.setClosed(true);
            FormularioAuditoria.setClosed(true);
            FormularioPedido.setClosed(true);
            FormularioBodega.setClosed(true);
            FormularioTipo.setClosed(true);
        } catch (PropertyVetoException ex) {
            JOptionPane.showMessageDialog(null,"No es posible salir"+ex.getMessage() );
        }
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemClienteActionPerformed
        FormularioCliente.setVisible(true);
        FormularioCliente.setLocation(150, 50);
    }//GEN-LAST:event_itemClienteActionPerformed

    private void escritorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_escritorioMouseClicked

    private void itemProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProductoActionPerformed
        FormularioProducto.setVisible(true);
        FormularioProducto.setLocation(20, 50);
    }//GEN-LAST:event_itemProductoActionPerformed

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
        FormularioProveedor.setVisible(true);
         FormularioProveedor.setLocation(150, 50);
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        FormularioEmpleado.setVisible(true);
        FormularioEmpleado.setLocation(150, 50);
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraActionPerformed
        FormularioCompra.setVisible(true);
        FormularioCompra.setLocation(150,50);
    }//GEN-LAST:event_itemCompraActionPerformed

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        FormularioUsuario.setVisible(true);
        FormularioUsuario.setLocation(300, 10);
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAuditoriaActionPerformed
        FormularioAuditoria.setVisible(true);
        FormularioAuditoria.setLocation(150, 50);
    }//GEN-LAST:event_itemAuditoriaActionPerformed

    private void itemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPedidoActionPerformed
       FormularioPedido.setVisible(true);
       FormularioPedido.setLocation(40, 30);
    }//GEN-LAST:event_itemPedidoActionPerformed

    private void itemmBodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemmBodegaActionPerformed
       FormularioBodega.setVisible(true);
       FormularioBodega.setLocation(150, 20);       
    }//GEN-LAST:event_itemmBodegaActionPerformed

    private void itemTipoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipoProductoActionPerformed
        FormularioTipo.setVisible(true);
        FormularioTipo.setLocation(150, 50);
    }//GEN-LAST:event_itemTipoProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDISistemaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDISistemaCliente().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MNUAdministrar;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JCheckBoxMenuItem itemAuditoria;
    private javax.swing.JMenu itemBodega;
    private javax.swing.JCheckBoxMenuItem itemCliente;
    private javax.swing.JCheckBoxMenuItem itemCompra;
    private javax.swing.JCheckBoxMenuItem itemEmpleado;
    private javax.swing.JCheckBoxMenuItem itemPedido;
    private javax.swing.JCheckBoxMenuItem itemProducto;
    private javax.swing.JCheckBoxMenuItem itemProveedor;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JCheckBoxMenuItem itemTipoProducto;
    private javax.swing.JCheckBoxMenuItem itemUsuario;
    private javax.swing.JCheckBoxMenuItem itemmBodega;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
